package com.abctreinamentos;
// Generated 29/12/2018 10:54:53 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 8983108385357328754L;
	private long cpf;
	private String nome;
	private String email;
	private Set<Pagamento> pagamentos = new HashSet<>();

	public Cliente() {
	}

	public Cliente(long cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public Cliente(long cpf, String nome, String email, Set<Pagamento> pagamentos) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
		this.pagamentos = pagamentos;
	}

	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Pagamento> getPagamentos() {
		return this.pagamentos;
	}

	public void setPagamentos(Set<Pagamento> pagamentos) {
		this.pagamentos = pagamentos;
	}
	
	@Override
	public String toString() {
		return "Cliente - cpf: " + cpf + " nome: " + nome + " e-mail: " + email;
	}
}
