package com.abctreinamentos;
// Generated 29/12/2018 10:54:53 by Hibernate Tools 5.2.11.Final

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private static final long serialVersionUID = 8252988904733033992L;
	private PagamentoId id;
	private Cliente cliente;
	private Curso curso;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, Cliente cliente, Curso curso) {
		this.id = id;
		this.cliente = cliente;
		this.curso = curso;
	}

	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@Override
	public String toString() {
		return cliente.toString() 
				+ "\n" + curso.toString()
				+ "\nInscrição feita em: " + id.getDatainscricao();
	}
}
